from __future__ import annotations

import json
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


class BridgeError(ValueError):
    """Raised when an XForge-to-SURE bridge manifest is invalid."""


SURE_MODELS_AGENT_CONTRACT = "docs/agents/model_tool_agent/AGENTS.md"


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _require_mapping(value: Any, name: str) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise BridgeError(f"{name} must be a JSON object")
    return value


def _require_fields(data: dict[str, Any], fields: tuple[str, ...], context: str) -> None:
    missing = [field for field in fields if field not in data or data[field] in (None, "")]
    if missing:
        raise BridgeError(f"{context} missing required field(s): {', '.join(missing)}")


def _read_json(path: Path) -> dict[str, Any]:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise BridgeError(f"invalid JSON at {path}: {exc}") from exc
    return _require_mapping(data, str(path))


def _write_json(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def _write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _write_text_if_missing(path: Path, text: str, executable: bool = False) -> bool:
    if path.exists():
        return False
    _write_text(path, text)
    if executable:
        path.chmod(path.stat().st_mode | 0o111)
    return True


def _write_generated_text(path: Path, text: str, executable: bool = False) -> bool:
    if path.exists():
        existing = path.read_text(encoding="utf-8", errors="ignore")
        generated_markers = (
            "sure_feed",
            "xforge-onboarding",
            "SURE_XFORGE_STATIC_ONLY=1",
            "Generated by XForge-SURE bridge",
            "package = false",
        )
        if not any(marker in existing for marker in generated_markers):
            return False
    _write_text(path, text)
    if executable:
        path.chmod(path.stat().st_mode | 0o111)
    return True


def _copy_path(source: Path, destination: Path) -> Path:
    if not source.exists():
        raise BridgeError(f"source path does not exist: {source}")
    destination.parent.mkdir(parents=True, exist_ok=True)
    if source.is_dir():
        if destination.exists():
            shutil.rmtree(destination)
        shutil.copytree(source, destination)
    else:
        shutil.copy2(source, destination)
    return destination.resolve()


def _path_is_relative_to(path: Path, parent: Path) -> bool:
    try:
        path.resolve().relative_to(parent.resolve())
    except ValueError:
        return False
    return True


def _materialize_model_path(
    source: Path,
    destination: Path,
    runtime_root: Path,
    source_metadata: dict[str, Any],
) -> tuple[Path, dict[str, Any]]:
    if not source.exists():
        raise BridgeError(f"source path does not exist: {source}")
    destination.parent.mkdir(parents=True, exist_ok=True)

    original_source = source_metadata.get("original_source")
    original_provider = original_source.get("provider") if isinstance(original_source, dict) else None
    source_is_runtime_cache = _path_is_relative_to(source, runtime_root)
    if original_provider in {"modelscope", "huggingface"} and source_is_runtime_cache:
        materialization = {
            "materialization_strategy": f"{original_provider}_runtime_cache",
            "checkpoint_materialized": False,
            "provider_cache_path": str(source.resolve()),
        }
        return source.resolve(), materialization

    local_model_path = _copy_path(source, destination)
    materialization = {
        "materialization_strategy": "copy_from_local_source",
        "checkpoint_materialized": True,
        "provider_cache_path": None,
    }
    return local_model_path, materialization


def _resolve_record_value(record: dict[str, Any], field: str) -> Any:
    value: Any = record
    for part in field.split("."):
        if not isinstance(value, dict) or part not in value:
            raise BridgeError(f"record missing mapped field: {field}")
        value = value[part]
    return value


def _load_optional_json(path: Path) -> dict[str, Any] | None:
    if not path.exists():
        return None
    return _read_json(path)


def _yaml_string(value: Any) -> str:
    return json.dumps("" if value is None else str(value), ensure_ascii=False)


def _path_for_spec(path: str | Path | None, root: Path) -> str | None:
    if path in (None, ""):
        return None
    resolved = Path(str(path)).resolve()
    try:
        relative = resolved.relative_to(root.resolve())
    except ValueError:
        return str(resolved)
    return f"./{relative.as_posix()}"


def _modelscope_model_url(source: dict[str, Any]) -> str:
    if source.get("url"):
        return str(source["url"])
    if source.get("provider") == "modelscope":
        return f"https://modelscope.cn/models/{source['id']}"
    return str(source.get("id") or "")


def _canonical_task_type(task_type: str) -> str:
    value = str(task_type or "").strip().lower()
    normalized = value.replace("-", "_")
    if normalized in {"speech_enhancement", "acoustic_noise_suppression"}:
        return "se"
    return value


def _sure_task_name(task_type: str) -> str:
    mapping = {
        "asr": "ASR",
        "s2tt": "S2TT",
        "slu": "SLU",
        "gr": "GR",
        "ser": "SER",
        "tts": "TTS",
        "se": "SE",
    }
    return mapping.get(task_type.lower(), task_type.upper())


def _default_tool_name(task_type: str) -> str:
    mapping = {
        "asr": "asr_transcribe",
        "s2tt": "s2tt_translate",
        "slu": "slu_understand",
        "gr": "gender_recognize",
        "ser": "emotion_recognize",
        "tts": "tts_synthesize",
        "kws": "kws_predict",
        "se": "enhance_speech",
    }
    return mapping.get(task_type.lower(), f"{task_type.lower()}_predict")


def _io_contract_for_task(task_type: str) -> dict[str, Any]:
    task = task_type.lower()
    if task == "tts":
        return {
            "input_field": "text",
            "input_type": "text",
            "output_type": "audio_path",
            "primary_field": "audio_path",
            "required_fields": ["audio_path"],
            "nonempty_fields": ["audio_path"],
        }
    if task == "kws":
        return {
            "input_field": "audio_path",
            "input_type": "audio_path",
            "output_type": "keyword_detection",
            "primary_field": "detected",
            "required_fields": ["detected", "keyword", "score"],
            "nonempty_fields": ["detected"],
        }
    if task == "se":
        return {
            "input_field": "audio_path",
            "input_type": "audio_path",
            "output_type": "audio",
            "primary_field": "audio_path",
            "required_fields": ["audio_path"],
            "nonempty_fields": ["audio_path"],
        }
    return {
        "input_field": "audio_path",
        "input_type": "audio_path",
        "output_type": "text",
        "primary_field": "text",
        "required_fields": ["text"],
        "nonempty_fields": ["text"],
    }


def _tool_input_schema_for_task(task_type: str) -> dict[str, Any]:
    task = task_type.lower()
    if task == "kws":
        return {
            "type": "object",
            "properties": {
                "audio_path": {"type": "string"},
                "keywords": {
                    "oneOf": [
                        {"type": "string", "minLength": 1},
                        {
                            "type": "array",
                            "minItems": 1,
                            "items": {"type": "string", "minLength": 1},
                        },
                    ]
                },
                "threshold": {"type": "number", "const": 0.5},
            },
            "required": ["audio_path"],
        }
    if task == "se":
        return {
            "type": "object",
            "properties": {
                "audio_path": {"type": "string"},
                "output_path": {"type": "string"},
            },
            "required": ["audio_path"],
        }
    input_field = "text" if task == "tts" else "audio_path"
    return {
        "type": "object",
        "properties": {
            input_field: {"type": "string"},
            "language": {"type": "string", "default": "auto"},
        },
        "required": [input_field],
    }


def _docker_image_tag(model_name: str) -> str:
    safe = "".join(char.lower() if char.isalnum() else "-" for char in model_name)
    safe = "-".join(part for part in safe.split("-") if part)
    return f"sure-{safe}:xforge-onboarding"


def _default_model_spec_yaml(
    manifest: dict[str, Any],
    model_root: Path,
    weights_manifest: dict[str, Any] | None,
) -> str:
    source = _require_mapping(manifest["source"], "source")
    model_id = model_root.name
    task_type = _canonical_task_type(str(manifest["task_type"]))
    io_contract = _io_contract_for_task(task_type)
    local_path = None
    if weights_manifest:
        local_path = _path_for_spec(weights_manifest.get("resolved_local_model_path"), model_root)
    local_path = local_path or "./checkpoints"
    runtime_root = "./.runtime"
    local_dir_name = "checkpoints"
    if weights_manifest:
        runtime_root = _path_for_spec(weights_manifest.get("runtime_root"), model_root) or runtime_root
        if str(weights_manifest.get("materialization_strategy", "")).endswith("_runtime_cache"):
            local_dir_name = ".runtime/modelscope_cache"

    lines = [
        "# Generated by sure_feed for SURE model-agent onboarding.",
        "# The SURE tool-agent must validate and revise this draft before evaluation.",
        f"model_id: {_yaml_string(model_id)}",
        f"model_name: {_yaml_string(manifest['model_name'])}",
        f"task_type: {_yaml_string(task_type)}",
        'deployment_type: "local"',
        "repo:",
        f"  url: {_yaml_string(_modelscope_model_url(source))}",
        "  commit: null",
        "weights:",
        f"  source: {_yaml_string(source['provider'])}",
        f"  repo_id: {_yaml_string(source['id'])}",
        f"  local_path: {_yaml_string(local_path)}",
        "  required: true",
        '  cache_policy: "model_local_first"',
        f"  local_dir_name: {_yaml_string(local_dir_name)}",
        "environment:",
        '  preferred_backend: "docker"',
        '  python_version: "3.12"',
        "  requires_gpu: true",
        "  system_packages:",
        '    - "ffmpeg"',
        "  runtime_root: " + _yaml_string(runtime_root),
        "entrypoints:",
        '  import_test: ""',
        '  load_test: ""',
        '  infer_test: ""',
        "io_contract:",
        f"  input_type: {_yaml_string(io_contract['input_type'])}",
        f"  output_type: {_yaml_string(io_contract['output_type'])}",
        f"  primary_field: {_yaml_string(io_contract['primary_field'])}",
        "  required_fields:",
        *[f"    - {_yaml_string(field)}" for field in io_contract["required_fields"]],
        "  nonempty_fields:",
        *[f"    - {_yaml_string(field)}" for field in io_contract["nonempty_fields"]],
        "  json_serializable: true",
        "acceptance:",
        "  must_import: true",
        "  must_load: true",
        "  must_infer: true",
        "  must_return_nonempty: true",
        "xforge:",
        '  generated_by: "xforge_modelscope_fetch"',
        f"  generated_at: {_yaml_string(_utc_now())}",
        f"  source_manifest: {_yaml_string(str(manifest.get('_manifest_path', '')))}",
    ]
    return "\n".join(lines) + "\n"


def _default_config_yaml(
    manifest: dict[str, Any],
    model_root: Path,
    weights_manifest: dict[str, Any] | None,
) -> str:
    source = _require_mapping(manifest["source"], "source")
    task_type = _canonical_task_type(str(manifest["task_type"]))
    sure_task = _sure_task_name(task_type)
    tool_name = _default_tool_name(task_type)
    io_contract = _io_contract_for_task(task_type)
    input_field = io_contract["input_field"]
    input_description = "Text to synthesize" if input_field == "text" else "Path to an audio file"
    if task_type in {"kws", "se"}:
        input_schema_block = (
            "    input_schema: "
            + json.dumps(_tool_input_schema_for_task(task_type), ensure_ascii=False, separators=(",", ":"))
        )
    else:
        input_schema_block = f"""    input_schema:
      type: object
      properties:
        {input_field}:
          type: string
          description: \"{input_description}\"
        language:
          type: string
          description: \"Language hint\"
          default: \"auto\"
      required: [{_yaml_string(input_field)}]"""
    model_path = str(source["id"])
    if weights_manifest:
        model_path = _path_for_spec(weights_manifest.get("resolved_local_model_path"), model_root) or model_path
    return f"""# Generated by sure_feed. The SURE model tool-agent must validate and revise.
name: {model_root.name}
task: {sure_task}
description: "ModelScope model {source['id']} prepared for SURE onboarding"
version: "0.1.0"

model:
  id: {_yaml_string(source['id'])}
  provider: {_yaml_string(source['provider'])}
  url: {_yaml_string(_modelscope_model_url(source))}

server:
  command: [".venv/bin/python", "server.py"]
  working_dir: "."
  env:
    MODEL_PATH: {_yaml_string(model_path)}
    MODELSCOPE_CACHE: "./.runtime/modelscope_cache"
    DEVICE: "auto"
  timeout: 600
  startup_timeout_sec: 300

tools:
  - name: {_yaml_string(tool_name)}
    description: "Run {sure_task} inference through the model-local wrapper"
{input_schema_block}

resources:
  memory_gb: 24
  gpu: true
  cpu_cores: 8
  storage_gb: 16
"""


def _default_pyproject(model_name: str) -> str:
    package_name = model_name.lower().replace("_", "-")
    return f"""[project]
name = "{package_name}"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  "modelscope[audio]",
  "torch",
  "transformers",
  "accelerate",
  "librosa>=0.10.0",
  "numpy",
  "scipy",
  "soundfile",
  "pyyaml",
]

[tool.uv]
package = false
"""


def _default_requirements_xforge() -> str:
    return """# Generated by sure_feed for SURE model onboarding.
# The SURE model tool-agent may pin or replace these after inspecting the repo.
modelscope[audio]
torch
transformers
accelerate
librosa>=0.10.0
numpy
scipy
soundfile
pyyaml
"""


def _default_requirements_local() -> str:
    return """# Generated by sure_feed for SURE tool-agent local bootstrap.
# Keep this file lightweight. Model runtime dependencies belong in
# requirements-xforge.txt and Docker until the tool-agent confirms otherwise.
"""


def _default_init_py() -> str:
    return '''"""Model-local SURE wrapper exports generated by sure_feed."""

from .model import ModelWrapper, PredictionResult

__all__ = ["ModelWrapper", "PredictionResult"]
'''


def _default_model_py(manifest: dict[str, Any]) -> str:
    source = _require_mapping(manifest["source"], "source")
    task_type = _canonical_task_type(str(manifest["task_type"]))
    if task_type == "tts":
        predict_body = '''        text = input_data.get("text") if isinstance(input_data, dict) else input_data
        if not text:
            raise ValueError("text is required")
        if not self.model_loaded:
            self.load()
        raise NotImplementedError("SURE tool-agent must implement TTS inference.")'''
        result_fields = '''    text: str = ""
    audio_path: str = ""
    language: str = "auto"
    raw: dict[str, Any] | None = None'''
    elif task_type == "kws":
        predict_body = '''        if not isinstance(input_data, dict):
            raise ValueError("KWS input must contain audio_path")
        audio_path = input_data.get("audio_path")
        keywords = input_data.get("keywords")
        if not audio_path:
            raise ValueError("audio_path is required")
        if not Path(str(audio_path)).exists():
            raise FileNotFoundError(str(audio_path))
        if keywords is not None:
            if isinstance(keywords, str):
                keywords_valid = bool(keywords.strip())
            else:
                keywords_valid = (
                    isinstance(keywords, list)
                    and bool(keywords)
                    and all(isinstance(keyword, str) and bool(keyword.strip()) for keyword in keywords)
                )
            if not keywords_valid:
                raise ValueError("keywords must be a non-empty string or list of strings when provided")
        if not self.model_loaded:
            self.load()
        raise NotImplementedError("SURE tool-agent must implement KWS inference.")'''
        result_fields = '''    detected: bool = False
    keyword: str | None = None
    score: float | None = None
    raw: dict[str, Any] | None = None'''
    elif task_type == "se":
        predict_body = '''        if not isinstance(input_data, dict):
            raise ValueError("SE input must contain audio_path")
        audio_path = input_data.get("audio_path")
        output_path = input_data.get("output_path")
        if not isinstance(audio_path, str) or not audio_path.strip():
            raise ValueError("audio_path is required")
        if not Path(audio_path).is_file():
            raise FileNotFoundError(audio_path)
        if output_path is not None and (not isinstance(output_path, str) or not output_path.strip()):
            raise ValueError("output_path must be a non-empty string when provided")
        if not self.model_loaded:
            self.load()
        raise NotImplementedError("SURE tool-agent must implement speech enhancement inference.")'''
        result_fields = '''    audio_path: str = ""
    raw: dict[str, Any] | None = None'''
    else:
        predict_body = '''        audio_path = input_data.get("audio_path") if isinstance(input_data, dict) else input_data
        if not audio_path:
            raise ValueError("audio_path is required")
        if not Path(str(audio_path)).exists():
            raise FileNotFoundError(str(audio_path))
        if not self.model_loaded:
            self.load()
        raise NotImplementedError("SURE tool-agent must implement inference.")'''
        result_fields = '''    text: str = ""
    audio_path: str = ""
    language: str = "auto"
    raw: dict[str, Any] | None = None'''
    return f'''"""SURE model wrapper scaffold for {source["id"]}.

This file is generated by sure_feed so the SURE model tool-agent can
continue from docs/agents/model_tool_agent/AGENTS.md. The model-specific load/infer
logic must be completed by that tool-agent after inspecting the downloaded
repository and its README/code.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any


@dataclass
class PredictionResult:
{result_fields}

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


class ModelWrapper:
    def __init__(self, config: dict[str, Any] | None = None):
        self.config = config or {{}}
        self.model_path = self.config.get("model_path") or "{source["id"]}"
        self.model_loaded = False

    def load(self) -> None:
        raise NotImplementedError(
            "SURE tool-agent must implement model-specific loading for {source["id"]}. "
            "Use the downloaded checkpoint path from artifacts/weights_manifest.json."
        )

    def predict(self, input_data: Any) -> PredictionResult:
{predict_body}

    def healthcheck(self) -> dict[str, Any]:
        return {{
            "status": "pending_tool_agent",
            "message": "Generated scaffold; model-specific load/infer is not implemented yet.",
            "model_loaded": self.model_loaded,
            "model_path": self.model_path,
        }}
'''


def _default_server_py(task_type: str) -> str:
    tool_name = _default_tool_name(task_type)
    io_contract = _io_contract_for_task(task_type)
    content_field = io_contract["primary_field"]
    input_schema = json.dumps(
        _tool_input_schema_for_task(task_type), ensure_ascii=False, separators=(",", ":")
    )
    content_value = (
        "json.dumps(result, ensure_ascii=False)"
        if task_type.lower() in {"kws", "se"}
        else f'str(result.get("{content_field}", ""))'
    )
    return f'''#!/usr/bin/env python3
"""Minimal MCP-style server scaffold generated by sure_feed."""

from __future__ import annotations

import json
import os
import sys
from typing import Any


class MCPServer:
    def __init__(self) -> None:
        self._initialized = False
        self._model = None
        self._tools = [{{
            "name": "{tool_name}",
            "description": "Run model-local inference",
            "inputSchema": {input_schema},
        }}]

    def _load_model(self):
        if self._model is None:
            from model import ModelWrapper

            self._model = ModelWrapper({{"model_path": os.environ.get("MODEL_PATH")}})
        return self._model

    def _handle_request(self, request: dict[str, Any]) -> dict[str, Any] | None:
        method = request.get("method")
        request_id = request.get("id")
        if method == "initialize":
            self._initialized = True
            return {{
                "jsonrpc": "2.0",
                "id": request_id,
                "result": {{
                    "protocolVersion": "2024-11-05",
                    "capabilities": {{"tools": {{}}}},
                    "serverInfo": {{"name": "xforge-sure-model-server", "version": "0.1.0"}},
                }},
            }}
        if method == "notifications/initialized":
            return None
        if method == "tools/list":
            return {{"jsonrpc": "2.0", "id": request_id, "result": {{"tools": self._tools}}}}
        if method == "tools/call":
            params = request.get("params", {{}})
            arguments = params.get("arguments", {{}})
            try:
                result = self._load_model().predict(arguments).to_dict()
                return {{
                    "jsonrpc": "2.0",
                    "id": request_id,
                    "result": {{"content": [{{"type": "text", "text": {content_value}}}], "raw": result}},
                }}
            except Exception as exc:
                return {{
                    "jsonrpc": "2.0",
                    "id": request_id,
                    "result": {{"content": [{{"type": "text", "text": f"Error: {{exc}}"}}], "isError": True}},
                }}
        return {{"jsonrpc": "2.0", "id": request_id, "error": {{"code": -32601, "message": str(method)}}}}

    def run(self) -> None:
        for line in sys.stdin:
            line = line.strip()
            if not line:
                continue
            try:
                response = self._handle_request(json.loads(line))
            except Exception as exc:
                response = {{"jsonrpc": "2.0", "id": None, "error": {{"code": -32603, "message": str(exc)}}}}
            if response is not None:
                print(json.dumps(response, ensure_ascii=False), flush=True)


if __name__ == "__main__":
    MCPServer().run()
'''


def _default_validate_py() -> str:
    return '''#!/usr/bin/env python3
"""SURE onboarding validation scaffold generated by sure_feed."""

from __future__ import annotations

import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path


MODEL_DIR = Path(__file__).resolve().parent
ARTIFACTS_DIR = MODEL_DIR / "artifacts"
VALIDATION_LOG = ARTIFACTS_DIR / "validation.log"


def _log(stage: str, status: str, message: str) -> None:
    ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)
    payload = {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "stage": stage,
        "status": status,
        "message": message,
    }
    with VALIDATION_LOG.open("a", encoding="utf-8") as handle:
        handle.write(json.dumps(payload, ensure_ascii=True) + "\\n")


def validate_static() -> int:
    required = [
        "model.spec.yaml",
        "config.yaml",
        "model.py",
        "server.py",
        "__init__.py",
        "artifacts/backend_choice.json",
        "artifacts/build_plan.json",
        "artifacts/xforge_sure_handoff.json",
    ]
    missing = [item for item in required if not (MODEL_DIR / item).exists()]
    if missing:
        _log("VALIDATE_SPEC", "failed", "Missing required files: " + ", ".join(missing))
        return 2
    _log("VALIDATE_SPEC", "passed", "Static onboarding files are present.")
    return 0


def main() -> int:
    static_status = validate_static()
    if static_status != 0:
        return static_status
    if os.environ.get("SURE_XFORGE_STATIC_ONLY", "0") == "1":
        return 0

    sys.path.insert(0, str(MODEL_DIR))
    from model import ModelWrapper

    wrapper = ModelWrapper()
    health = wrapper.healthcheck()
    _log("VALIDATE_IMPORT", "passed", "ModelWrapper imported; health=" + json.dumps(health))
    _log("VALIDATE_LOAD", "pending_tool_agent", "Generated scaffold cannot load model-specific weights yet.")
    return 3


if __name__ == "__main__":
    raise SystemExit(main())
'''


def _default_dockerfile(model_root: Path) -> str:
    venv_path = f"/opt/{model_root.name}_venv"
    model_dir = f"/workspace/sure-eval/sure/models/{model_root.name}"
    return f'''# Generated by sure_feed for SURE model onboarding.
ARG BASE_IMAGE=pytorch/pytorch:2.4.1-cuda12.1-cudnn9-devel
FROM ${{BASE_IMAGE}}

ARG DEBIAN_FRONTEND=noninteractive
ARG UV_VERSION=0.7.13

ENV PYTHONDONTWRITEBYTECODE=1 \\
    PYTHONUNBUFFERED=1 \\
    PIP_NO_CACHE_DIR=1 \\
    UV_PROJECT_ENVIRONMENT={venv_path} \\
    VIRTUAL_ENV={venv_path} \\
    PATH="{venv_path}/bin:/root/.local/bin:${{PATH}}" \\
    SURE_EVAL_ROOT=/workspace/sure-eval \\
    MODEL_DIR={model_dir} \\
    MODEL_PATH={model_dir}/.runtime/modelscope_cache \\
    MODELSCOPE_CACHE={model_dir}/.runtime/modelscope_cache \\
    HF_HOME={model_dir}/.runtime/huggingface \\
    HF_HUB_CACHE={model_dir}/.runtime/huggingface/hub \\
    DEVICE=auto

RUN apt-get update \\
    && apt-get install -y --no-install-recommends \\
        build-essential \\
        ca-certificates \\
        curl \\
        ffmpeg \\
        git \\
        libsndfile1 \\
        wget \\
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace/sure-eval

COPY pyproject.toml uv.lock requirements.txt ./
COPY sure ./sure

RUN python -m pip install --upgrade pip \\
    && python -m pip install "uv==${{UV_VERSION}}" \\
    && python -m venv --system-site-packages "${{VIRTUAL_ENV}}" \\
    && "${{VIRTUAL_ENV}}/bin/python" -m pip install --upgrade pip \\
    && "${{VIRTUAL_ENV}}/bin/python" -m pip install -r requirements.txt \\
    && "${{VIRTUAL_ENV}}/bin/python" -m pip install --no-deps -e . \\
    && "${{VIRTUAL_ENV}}/bin/python" -m pip install -r sure/models/{model_root.name}/requirements-xforge.txt

RUN mkdir -p "${{MODELSCOPE_CACHE}}" "${{HF_HUB_CACHE}}" "${{MODEL_DIR}}/artifacts" \\
    && chmod a+rwx "${{SURE_EVAL_ROOT}}" \\
    && chmod -R a+rwx "${{MODEL_DIR}}/.runtime" "${{MODEL_DIR}}/artifacts"

WORKDIR /workspace/sure-eval/sure/models/{model_root.name}

CMD ["{venv_path}/bin/python", "validate.py"]
'''


def _default_docker_build_sh(model_root: Path) -> str:
    image_tag = _docker_image_tag(model_root.name)
    return f'''#!/usr/bin/env bash
# Generated by sure_feed for SURE model onboarding.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${{BASH_SOURCE[0]}}")/../../../.." && pwd)"
IMAGE_TAG="${{IMAGE_TAG:-{image_tag}}}"
BASE_IMAGE="${{BASE_IMAGE:-pytorch/pytorch:2.4.1-cuda12.1-cudnn9-devel}}"
BUILD_LOG="${{BUILD_LOG:-${{REPO_ROOT}}/sure/models/{model_root.name}/artifacts/build.log}}"
mkdir -p "$(dirname "${{BUILD_LOG}}")"

cd "${{REPO_ROOT}}"
run_docker_checked() {{
  local output_file
  local status

  output_file="$(mktemp)"
  set +e
  "$@" 2>&1 | tee "${{output_file}}"
  status=${{PIPESTATUS[0]}}
  set -e

  cat "${{output_file}}" >> "${{BUILD_LOG}}"
  if [ "${{status}}" -ne 0 ] || grep -Eqi '^(ERROR:|Error:)|failed to solve|No such image' "${{output_file}}"; then
    rm -f "${{output_file}}"
    return 1
  fi
  rm -f "${{output_file}}"
}}

: > "${{BUILD_LOG}}"
run_docker_checked docker build \\
  --pull=false \\
  --build-arg "BASE_IMAGE=${{BASE_IMAGE}}" \\
  -f sure/models/{model_root.name}/Dockerfile \\
  -t "${{IMAGE_TAG}}" \\
  .

run_docker_checked docker image inspect "${{IMAGE_TAG}}" >/dev/null

echo "${{IMAGE_TAG}}"
'''


def _default_docker_validate_sh(model_root: Path) -> str:
    image_tag = _docker_image_tag(model_root.name)
    return f'''#!/usr/bin/env bash
# Generated by sure_feed for SURE model onboarding.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"
REPO_ROOT="$(cd "${{SCRIPT_DIR}}/../../../.." && pwd)"
REPO_ROOT="$(readlink -f "${{REPO_ROOT}}")"
IMAGE_TAG="${{IMAGE_TAG:-{image_tag}}}"
CONTAINER_MODEL_DIR="/workspace/sure-eval/sure/models/{model_root.name}"
CONTAINER_SRC_DIR="/workspace/sure-eval/sure"

MODEL_DIR="${{MODEL_DIR:-${{SCRIPT_DIR}}}}"
MODEL_DIR="$(readlink -f "${{MODEL_DIR}}")"

ARTIFACTS_DIR="${{ARTIFACTS_DIR:-${{MODEL_DIR}}/artifacts}}"
mkdir -p "${{ARTIFACTS_DIR}}"
ARTIFACTS_DIR="$(readlink -f "${{ARTIFACTS_DIR}}")"
chmod a+rwx "${{ARTIFACTS_DIR}}"

VALIDATION_LOG="${{VALIDATION_LOG:-${{ARTIFACTS_DIR}}/validation.log}}"

for required_path in \\
  "${{REPO_ROOT}}/sure/__init__.py" \\
  "${{REPO_ROOT}}/sure/models/__init__.py" \\
  "${{MODEL_DIR}}/model.py" \\
  "${{MODEL_DIR}}/validate.py" \\
  "${{MODEL_DIR}}/config.yaml" \\
  "${{MODEL_DIR}}/model.spec.yaml" \\
  "${{MODEL_DIR}}/server.py" \\
  "${{MODEL_DIR}}/checkpoints" \\
  "${{MODEL_DIR}}/.runtime"; do
  if [ ! -e "${{required_path}}" ]; then
    echo "Missing required path: ${{required_path}}" >&2
    exit 1
  fi
done

: > "${{VALIDATION_LOG}}"

docker run --rm \\
  -e SURE_XFORGE_STATIC_ONLY=1 \\
  -v "${{REPO_ROOT}}/sure/__init__.py:${{CONTAINER_SRC_DIR}}/__init__.py:ro" \\
  -v "${{REPO_ROOT}}/sure/models/__init__.py:${{CONTAINER_SRC_DIR}}/models/__init__.py:ro" \\
  -v "${{REPO_ROOT}}/sure/models/base.py:${{CONTAINER_SRC_DIR}}/models/base.py:ro" \\
  -v "${{REPO_ROOT}}/sure/models/registry.py:${{CONTAINER_SRC_DIR}}/models/registry.py:ro" \\
  -v "${{REPO_ROOT}}/sure/models/model_mapping.py:${{CONTAINER_SRC_DIR}}/models/model_mapping.py:ro" \\
  -v "${{MODEL_DIR}}/__init__.py:${{CONTAINER_MODEL_DIR}}/__init__.py:ro" \\
  -v "${{MODEL_DIR}}/model.py:${{CONTAINER_MODEL_DIR}}/model.py:ro" \\
  -v "${{MODEL_DIR}}/validate.py:${{CONTAINER_MODEL_DIR}}/validate.py:ro" \\
  -v "${{MODEL_DIR}}/config.yaml:${{CONTAINER_MODEL_DIR}}/config.yaml:ro" \\
  -v "${{MODEL_DIR}}/model.spec.yaml:${{CONTAINER_MODEL_DIR}}/model.spec.yaml:ro" \\
  -v "${{MODEL_DIR}}/server.py:${{CONTAINER_MODEL_DIR}}/server.py:ro" \\
  -v "${{MODEL_DIR}}/checkpoints:${{CONTAINER_MODEL_DIR}}/checkpoints:ro" \\
  -v "${{MODEL_DIR}}/.runtime:${{CONTAINER_MODEL_DIR}}/.runtime" \\
  -v "${{ARTIFACTS_DIR}}:${{CONTAINER_MODEL_DIR}}/artifacts" \\
  "${{IMAGE_TAG}}" \\
  bash -lc 'export PYTHONPATH=/workspace/sure-eval/src:${{PYTHONPATH:-}}; "${{VIRTUAL_ENV}}/bin/python" validate.py'

echo "Artifacts written to: ${{ARTIFACTS_DIR}}"
'''


def _default_local_uv_setup_sh() -> str:
    return '''#!/usr/bin/env bash
# Generated by sure_feed for SURE tool-agent local bootstrap.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../../.." && pwd)"
REPO_ROOT="$(readlink -f "${REPO_ROOT}")"
ARTIFACTS_DIR="${SCRIPT_DIR}/artifacts"
mkdir -p "${ARTIFACTS_DIR}"
LOG_PATH="${ARTIFACTS_DIR}/local_uv_setup.log"
export UV_CACHE_DIR="${SCRIPT_DIR}/.runtime/uv-cache"
mkdir -p "${UV_CACHE_DIR}"

cd "${SCRIPT_DIR}"

PYTHON_BIN="${PYTHON_BIN:-python3.12}"
if ! command -v "${PYTHON_BIN}" >/dev/null 2>&1; then
  PYTHON_BIN="${PYTHON_FALLBACK:-python3.11}"
fi
if ! command -v "${PYTHON_BIN}" >/dev/null 2>&1; then
  PYTHON_BIN="python3"
fi
if ! command -v "${PYTHON_BIN}" >/dev/null 2>&1; then
  echo "No usable Python found. Tried python3.12, python3.11, and python3" | tee "${LOG_PATH}" >&2
  exit 1
fi
if ! command -v uv >/dev/null 2>&1; then
  echo "uv is required for local tool-agent bootstrap" | tee "${LOG_PATH}" >&2
  exit 1
fi

{
  echo "PYTHON_BIN=${PYTHON_BIN}"
  uv --version
  uv venv --python "${PYTHON_BIN}" .venv
  uv pip install --python .venv/bin/python -r requirements-local.txt
  if [ "${INSTALL_SURE_EDITABLE:-0}" = "1" ] && [ -f "${REPO_ROOT}/pyproject.toml" ]; then
    uv pip install --python .venv/bin/python --no-deps -e "${REPO_ROOT}"
  fi
  .venv/bin/python --version
} 2>&1 | tee "${LOG_PATH}"

.venv/bin/python - <<'PY'
import json
import platform
from datetime import datetime, timezone
from pathlib import Path

model_dir = Path(__file__).resolve().parent
artifacts = model_dir / "artifacts"
payload = {
    "status": "setup_completed",
    "checked_at": datetime.now(timezone.utc).isoformat(),
    "venv_path": str((model_dir / ".venv").resolve()),
    "python": {
        "path": str((model_dir / ".venv" / "bin" / "python").resolve()),
        "version": platform.python_version(),
    },
    "setup_log": str((artifacts / "local_uv_setup.log").resolve()),
}
(artifacts / "local_uv_env.json").write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\\n", encoding="utf-8")
PY
'''


def _default_local_uv_validate_sh() -> str:
    return '''#!/usr/bin/env bash
# Generated by sure_feed for SURE tool-agent local bootstrap.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../../.." && pwd)"
REPO_ROOT="$(readlink -f "${REPO_ROOT}")"
ARTIFACTS_DIR="${SCRIPT_DIR}/artifacts"
mkdir -p "${ARTIFACTS_DIR}"
LOG_PATH="${ARTIFACTS_DIR}/local_uv_validate.log"

cd "${SCRIPT_DIR}"
if [ ! -x ".venv/bin/python" ]; then
  echo "Missing model-local .venv. Run local_uv_setup.sh first." | tee "${LOG_PATH}" >&2
  exit 1
fi

{
  .venv/bin/python --version
  PYTHONPATH="${REPO_ROOT}/src:${PYTHONPATH:-}" SURE_XFORGE_STATIC_ONLY=1 .venv/bin/python validate.py
} 2>&1 | tee "${LOG_PATH}"

.venv/bin/python - <<'PY'
import json
import platform
from datetime import datetime, timezone
from pathlib import Path

model_dir = Path(__file__).resolve().parent
artifacts = model_dir / "artifacts"
payload = {
    "status": "passed",
    "checked_at": datetime.now(timezone.utc).isoformat(),
    "venv_path": str((model_dir / ".venv").resolve()),
    "python": {
        "path": str((model_dir / ".venv" / "bin" / "python").resolve()),
        "version": platform.python_version(),
    },
    "validation_log": str((artifacts / "local_uv_validate.log").resolve()),
}
(artifacts / "local_uv_validation.json").write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\\n", encoding="utf-8")
PY
'''


def _emit_preflight_summary(model_root: Path, checkpoints_dir: Path, runtime_dir: Path) -> dict[str, Any]:
    artifacts_dir = model_root / "artifacts"
    disk = shutil.disk_usage(model_root)
    payload = {
        "status": "completed_static",
        "checked_at": _utc_now(),
        "python": {
            "preferred": "python3.12",
            "preferred_available": shutil.which("python3.12") is not None,
            "fallback": shutil.which("python3") or sys.executable,
            "current_executable": sys.executable,
        },
        "package_managers": {
            "uv": {"available": shutil.which("uv") is not None, "path": shutil.which("uv")},
            "pip": {"available": shutil.which("pip") is not None, "path": shutil.which("pip")},
            "docker": {"available": shutil.which("docker") is not None, "path": shutil.which("docker")},
        },
        "model_local_paths": {
            "checkpoint_root": str(checkpoints_dir.resolve()),
            "runtime_root": str(runtime_dir.resolve()),
            "venv_path": str((model_root / ".venv").resolve()),
            "artifacts": str(artifacts_dir.resolve()),
        },
        "local_uv_env": {
            "status": "venv_present_pending_validation"
            if (model_root / ".venv" / "bin" / "python").exists()
            else "generated_pending_execution",
            "setup_script": str((model_root / "local_uv_setup.sh").resolve()),
            "validate_script": str((model_root / "local_uv_validate.sh").resolve()),
            "requirements": str((model_root / "requirements-local.txt").resolve()),
        },
        "disk_space": {
            "model_dir_total_gb": round(disk.total / (1024**3), 3),
            "model_dir_free_gb": round(disk.free / (1024**3), 3),
        },
        "warnings": [],
    }
    if not payload["python"]["preferred_available"]:
        payload["warnings"].append("python3.12 is not available; local_uv_setup.sh will fall back to python3 unless PYTHON_BIN is set.")
    if not payload["package_managers"]["uv"]["available"]:
        payload["warnings"].append("uv is not available on PATH; local uv bootstrap will fail until uv is installed or PATH is fixed.")
    _write_json(artifacts_dir / "preflight_summary.json", payload)
    return payload


def _emit_local_uv_env(model_root: Path) -> dict[str, Any]:
    artifacts_dir = model_root / "artifacts"
    venv_python = model_root / ".venv" / "bin" / "python"
    validation_path = artifacts_dir / "local_uv_validation.json"
    validation = _load_optional_json(validation_path)
    if validation and validation.get("status") == "passed" and venv_python.exists():
        status = "ready"
    elif venv_python.exists():
        status = "venv_present_pending_validation"
    else:
        status = "generated_pending_execution"
    payload = {
        "status": status,
        "generated_at": _utc_now(),
        "venv_path": str((model_root / ".venv").resolve()),
        "python_path": str(venv_python.resolve()),
        "requirements": str((model_root / "requirements-local.txt").resolve()),
        "setup_command": f"sure/models/{model_root.name}/local_uv_setup.sh",
        "validate_command": f"sure/models/{model_root.name}/local_uv_validate.sh",
        "validation": str(validation_path.resolve()) if validation_path.exists() else None,
        "purpose": "model-local uv bootstrap for SURE tool-agent static validation and wrapper handoff",
    }
    _write_json(artifacts_dir / "local_uv_env.json", payload)
    return payload


def _emit_static_spec_validation(model_root: Path, has_weights: bool) -> dict[str, Any]:
    artifacts_dir = model_root / "artifacts"
    required_files = [
        "model.spec.yaml",
        "config.yaml",
        "pyproject.toml",
        "requirements-xforge.txt",
        "requirements-local.txt",
        "local_uv_setup.sh",
        "local_uv_validate.sh",
        "Dockerfile",
        "docker_build.sh",
        "docker_validate.sh",
        "model.py",
        "server.py",
        "validate.py",
        "__init__.py",
        "artifacts/backend_choice.json",
        "artifacts/preflight_summary.json",
        "artifacts/local_uv_env.json",
    ]
    if has_weights:
        required_files.append("artifacts/weights_manifest.json")
    missing = [item for item in required_files if not (model_root / item).exists()]
    status = "passed" if not missing else "failed"
    payload = {
        "status": status,
        "state": "VALIDATE_SPEC",
        "checked_at": _utc_now(),
        "required_files": required_files,
        "missing_files": missing,
        "next_state_if_passed": "DOCKER_BUILD_CONFIRM",
        "requires_user_confirmation_before_build": True,
    }
    _write_json(artifacts_dir / "spec_validation.json", payload)
    log_payload = {
        "timestamp": payload["checked_at"],
        "stage": "VALIDATE_SPEC",
        "status": status,
        "message": (
            "Static onboarding files are present; stop before docker build for user confirmation."
            if status == "passed"
            else "Missing required files: " + ", ".join(missing)
        ),
    }
    with (artifacts_dir / "validation.log").open("a", encoding="utf-8") as handle:
        handle.write(json.dumps(log_payload, ensure_ascii=True) + "\n")
    return payload


def collect_dataset_manifest(manifest: dict[str, Any], raw_root: str | Path) -> dict[str, Any]:
    """Collect a dataset resource into a local raw directory.

    This bridge keeps collection provider-neutral. XForge discovery selects the
    source; this function materializes local sources and records enough metadata
    for later processing. Network providers are intentionally delegated to their
    normal CLIs/libraries by the script entrypoint.
    """

    manifest = _require_mapping(manifest, "manifest")
    _require_fields(manifest, ("resource_type", "dataset_id", "source"), "dataset manifest")
    if manifest["resource_type"] != "dataset":
        raise BridgeError("dataset collection requires resource_type='dataset'")

    source = _require_mapping(manifest["source"], "source")
    _require_fields(source, ("provider", "id"), "dataset source")
    provider = str(source["provider"])
    dataset_id = str(manifest["dataset_id"])
    output_root = Path(raw_root)
    output_root.mkdir(parents=True, exist_ok=True)

    copied_path: str | None = None
    if provider == "local":
        source_path = Path(str(source["id"]))
        destination = output_root / source_path.name
        copied_path = str(_copy_path(source_path, destination))

    summary = {
        "resource_type": "dataset",
        "dataset_id": dataset_id,
        "provider": provider,
        "raw_root": str(output_root.resolve()),
        "copied_path": copied_path,
        "collected_at": _utc_now(),
        "next_step": "scripts/xforge_process_to_sure.py",
    }
    _write_json(output_root / "manifest.json", {**manifest, "collection_summary": summary})
    return summary


def process_dataset_manifest(manifest: dict[str, Any], output_path: str | Path) -> dict[str, Any]:
    """Transform an XForge raw dataset manifest into SURE JSONL."""

    manifest = _require_mapping(manifest, "manifest")
    _require_fields(
        manifest,
        ("resource_type", "dataset_id", "sure_name", "task", "language", "raw_root", "raw_jsonl"),
        "dataset manifest",
    )
    if manifest["resource_type"] != "dataset":
        raise BridgeError("dataset processing requires resource_type='dataset'")

    field_mapping = _require_mapping(manifest.get("field_mapping", {}), "field_mapping")
    _require_fields(field_mapping, ("key", "path", "target"), "field_mapping")

    raw_root = Path(str(manifest["raw_root"])).resolve()
    raw_jsonl = Path(str(manifest["raw_jsonl"]))
    if not raw_jsonl.is_absolute():
        raw_jsonl = raw_root / raw_jsonl
    if not raw_jsonl.exists():
        raise BridgeError(f"raw_jsonl does not exist: {raw_jsonl}")

    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    samples_written = 0

    with raw_jsonl.open("r", encoding="utf-8") as src, output.open("w", encoding="utf-8") as dst:
        for line_number, line in enumerate(src, 1):
            line = line.strip()
            if not line:
                continue
            try:
                record = json.loads(line)
            except json.JSONDecodeError as exc:
                raise BridgeError(f"invalid JSONL record {line_number} in {raw_jsonl}: {exc}") from exc
            record = _require_mapping(record, f"{raw_jsonl}:{line_number}")

            audio_value = str(_resolve_record_value(record, str(field_mapping["path"])))
            audio_path = Path(audio_value)
            if not audio_path.is_absolute():
                audio_path = raw_root / audio_path
            if not audio_path.exists():
                raise BridgeError(f"audio path does not exist at record {line_number}: {audio_path}")

            sample = {
                "key": str(_resolve_record_value(record, str(field_mapping["key"]))),
                "path": str(audio_path.resolve()),
                "target": str(_resolve_record_value(record, str(field_mapping["target"]))).strip(),
                "task": str(manifest["task"]),
                "language": str(record.get("language", manifest["language"])),
                "dataset": str(manifest["sure_name"]),
            }
            dst.write(json.dumps(sample, ensure_ascii=False) + "\n")
            samples_written += 1

    summary = {
        "resource_type": "dataset",
        "dataset_id": str(manifest["dataset_id"]),
        "sure_name": str(manifest["sure_name"]),
        "jsonl_path": str(output.resolve()),
        "samples_written": samples_written,
        "processed_at": _utc_now(),
    }
    return summary


def process_dataset_manifest_to_oref(
    manifest: dict[str, Any],
    datasets_root: str | Path,
    allow_missing_audio: bool = False,
) -> dict[str, Any]:
    """Transform an XForge raw dataset manifest into a local OREF dataset.

    This intentionally writes the OREF structure currently consumed by
    DatasetManager._convert_oref_jsonl_to_jsonl: audio files under audio/ and
    sample.jsonl records with annotation/attribute fields.
    """

    manifest = _require_mapping(manifest, "manifest")
    _require_fields(
        manifest,
        ("resource_type", "dataset_id", "sure_name", "task", "language", "raw_root", "raw_jsonl"),
        "dataset manifest",
    )
    if manifest["resource_type"] != "dataset":
        raise BridgeError("dataset OREF processing requires resource_type='dataset'")

    field_mapping = _require_mapping(manifest.get("field_mapping", {}), "field_mapping")
    _require_fields(field_mapping, ("key", "path", "target"), "field_mapping")

    dataset_name = str(manifest["sure_name"])
    raw_root = Path(str(manifest["raw_root"])).resolve()
    raw_jsonl = Path(str(manifest["raw_jsonl"]))
    if not raw_jsonl.is_absolute():
        raw_jsonl = raw_root / raw_jsonl
    if not raw_jsonl.exists():
        raise BridgeError(f"raw_jsonl does not exist: {raw_jsonl}")

    dataset_root = Path(datasets_root) / dataset_name
    audio_dir = dataset_root / "audio"
    sample_jsonl = dataset_root / "sample.jsonl"
    audio_dir.mkdir(parents=True, exist_ok=True)

    samples_written = 0
    missing_audio_count = 0
    with raw_jsonl.open("r", encoding="utf-8") as src, sample_jsonl.open("w", encoding="utf-8") as dst:
        for line_number, line in enumerate(src, 1):
            line = line.strip()
            if not line:
                continue
            try:
                record = json.loads(line)
            except json.JSONDecodeError as exc:
                raise BridgeError(f"invalid JSONL record {line_number} in {raw_jsonl}: {exc}") from exc
            record = _require_mapping(record, f"{raw_jsonl}:{line_number}")

            audio_value = str(_resolve_record_value(record, str(field_mapping["path"])))
            source_audio = Path(audio_value)
            if not source_audio.is_absolute():
                source_audio = raw_root / source_audio
            if not source_audio.exists() and not allow_missing_audio:
                raise BridgeError(f"audio path does not exist at record {line_number}: {source_audio}")

            target_audio = audio_dir / source_audio.name
            audio_missing = not source_audio.exists()
            if audio_missing:
                missing_audio_count += 1
            else:
                if target_audio.exists() and target_audio.resolve() != source_audio.resolve():
                    target_audio = audio_dir / f"{_resolve_record_value(record, str(field_mapping['key']))}_{source_audio.name}"
                shutil.copy2(source_audio, target_audio)

            text = str(_resolve_record_value(record, str(field_mapping["target"]))).strip()
            key = str(_resolve_record_value(record, str(field_mapping["key"])))
            sample_rate = record.get("sample_rate") or record.get("sampling_rate") or record.get("sr") or 16000
            duration = record.get("duration") or record.get("duration_ms") or 0
            language = str(record.get("language", manifest["language"]))
            oref_record = {
                "sample_id": key,
                "attribute": {
                    "path": f"audio/{target_audio.name}",
                    "sample_rate": sample_rate,
                    "duration": duration,
                    "language": language,
                    "missing_audio_placeholder": audio_missing,
                    "original_path": audio_value,
                },
                "annotation": [
                    {
                        "transcription": {
                            "text": [text],
                        }
                    }
                ],
                "task": str(manifest["task"]),
                "dataset": dataset_name,
            }
            dst.write(json.dumps(oref_record, ensure_ascii=False) + "\n")
            samples_written += 1

    registry_entry = {
        "config_name": dataset_name,
        "audio_dir": f"{dataset_name}/audio",
        "jsonl_path": f"{dataset_name}/sample.jsonl",
        "task": str(manifest["task"]),
        "language": str(manifest["language"]),
    }
    summary = {
        "resource_type": "dataset",
        "dataset_id": str(manifest["dataset_id"]),
        "sure_name": dataset_name,
        "oref_root": str(dataset_root.resolve()),
        "sample_jsonl": str(sample_jsonl.resolve()),
        "audio_dir": str(audio_dir.resolve()),
        "samples_written": samples_written,
        "missing_audio_count": missing_audio_count,
        "allow_missing_audio": allow_missing_audio,
        "registry_entry": registry_entry,
        "processed_at": _utc_now(),
    }
    _write_json(dataset_root / "oref_summary.json", summary)
    return summary


def write_oref_registry_entry(
    registry_path: str | Path,
    dataset_name: str,
    registry_entry: dict[str, Any],
) -> dict[str, Any]:
    """Add or update a dataset entry in config/oref_datasets.yaml format."""

    try:
        import yaml
    except ImportError as exc:
        raise BridgeError("pyyaml is required to update OREF dataset registry") from exc

    path = Path(registry_path)
    if path.exists():
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
        if not isinstance(data, dict):
            data = {}
    else:
        data = {}
    datasets = data.setdefault("datasets", {})
    if not isinstance(datasets, dict):
        raise BridgeError("OREF registry 'datasets' must be a mapping")
    data.setdefault("fallbacks", {})
    datasets[dataset_name] = dict(registry_entry)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(yaml.safe_dump(data, allow_unicode=True, sort_keys=True), encoding="utf-8")
    return {
        "registry_path": str(path.resolve()),
        "dataset_name": dataset_name,
        "entry": dict(registry_entry),
        "updated_at": _utc_now(),
    }


def plan_model_integration(
    manifest: dict[str, Any],
    manifest_path: str | Path,
    handoff_path: str | Path,
    model_dir: str | Path,
) -> dict[str, Any]:
    """Describe how a discovered model will be completed for SURE evaluation."""

    manifest = _require_mapping(manifest, "manifest")
    _require_fields(manifest, ("resource_type", "model_name", "task_type", "source"), "model manifest")
    if manifest["resource_type"] != "model":
        raise BridgeError("model integration planning requires resource_type='model'")

    source = _require_mapping(manifest["source"], "source")
    _require_fields(source, ("provider", "id"), "model source")

    model_root = Path(model_dir).resolve()
    checkpoints_dir = model_root / "checkpoints"
    artifacts_dir = model_root / "artifacts"
    return {
        "resource_type": "model",
        "provider": str(source["provider"]),
        "resource_id": str(source["id"]),
        "model_name": str(manifest["model_name"]),
        "task_type": str(manifest["task_type"]),
        "manifest_path": str(Path(manifest_path).resolve()),
        "handoff_path": str(Path(handoff_path).resolve()),
        "expected_model_dir": str(model_root),
        "expected_checkpoint_dir": str(checkpoints_dir),
        "expected_weights_manifest": str(artifacts_dir / "weights_manifest.json"),
        "required_wrapper": {
            "entrypoint": "model.py",
            "predict_contract": "docs/agents/model_tool_agent/specs/cli_predict_contract.md",
            "status": "not_generated",
        },
        "status": "waiting_for_checkpoint_download",
        "next_step": "download_checkpoint",
        "evaluation_ready": False,
        "planned_at": _utc_now(),
    }


def plan_dataset_integration(
    manifest: dict[str, Any],
    manifest_path: str | Path,
    handoff_path: str | Path,
    sure_dataset_dir: str | Path,
) -> dict[str, Any]:
    """Describe how a discovered dataset will be completed for SURE evaluation."""

    manifest = _require_mapping(manifest, "manifest")
    _require_fields(manifest, ("resource_type", "dataset_id", "sure_name", "task", "raw_root"), "dataset manifest")
    if manifest["resource_type"] != "dataset":
        raise BridgeError("dataset integration planning requires resource_type='dataset'")

    sure_name = str(manifest["sure_name"])
    return {
        "resource_type": "dataset",
        "provider": str(_require_mapping(manifest["source"], "source").get("provider", "modelscope")),
        "resource_id": str(manifest["dataset_id"]),
        "sure_name": sure_name,
        "task": str(manifest["task"]),
        "language": str(manifest.get("language") or "auto"),
        "manifest_path": str(Path(manifest_path).resolve()),
        "handoff_path": str(Path(handoff_path).resolve()),
        "expected_raw_root": str(manifest["raw_root"]),
        "expected_sure_jsonl": str((Path(sure_dataset_dir) / f"{sure_name}.jsonl").resolve()),
        "required_field_mapping": ["key", "path", "target"],
        "optional_field_mapping": ["language"],
        "schema_mapping_status": "required",
        "status": "waiting_for_raw_download_and_schema_mapping",
        "next_step": "confirm_dataset_schema",
        "evaluation_ready": False,
        "planned_at": _utc_now(),
    }


def emit_sure_model_agent_handoff(
    manifest: dict[str, Any],
    manifest_path: str | Path,
    handoff_path: str | Path,
    model_dir: str | Path,
) -> dict[str, Any]:
    """Emit model-local artifacts that let the SURE model tool-agent continue.

    XForge owns discovery and checkpoint placement. The SURE model harness owns
    spec validation, environment construction, wrapper generation, and inference
    contract validation according to docs/agents/model_tool_agent/AGENTS.md.
    """

    manifest = _require_mapping(manifest, "manifest")
    _require_fields(manifest, ("resource_type", "model_name", "task_type", "source"), "model manifest")
    if manifest["resource_type"] != "model":
        raise BridgeError("SURE model-agent handoff requires resource_type='model'")

    source = _require_mapping(manifest["source"], "source")
    _require_fields(source, ("provider", "id"), "model source")

    model_root = Path(model_dir)
    artifacts_dir = model_root / "artifacts"
    checkpoints_dir = model_root / "checkpoints"
    runtime_dir = model_root / ".runtime"
    artifacts_dir.mkdir(parents=True, exist_ok=True)
    checkpoints_dir.mkdir(parents=True, exist_ok=True)
    runtime_dir.mkdir(parents=True, exist_ok=True)

    manifest_path = Path(manifest_path)
    handoff_path = Path(handoff_path)
    weights_manifest_path = artifacts_dir / "weights_manifest.json"
    weights_manifest = _load_optional_json(weights_manifest_path)
    has_weights = weights_manifest is not None
    generated_at = _utc_now()
    model_name = str(manifest["model_name"])
    task_type = _canonical_task_type(str(manifest["task_type"]))

    normalized_manifest = {**manifest, "task_type": task_type}
    spec_manifest = {
        **normalized_manifest,
        "_manifest_path": str(manifest_path.resolve()),
    }
    spec_path = model_root / "model.spec.yaml"
    _write_text(spec_path, _default_model_spec_yaml(spec_manifest, model_root, weights_manifest))
    generated_scaffold = {
        "config_yaml": _write_generated_text(
            model_root / "config.yaml",
            _default_config_yaml(normalized_manifest, model_root, weights_manifest),
        ),
        "pyproject_toml": _write_generated_text(model_root / "pyproject.toml", _default_pyproject(model_root.name)),
        "requirements_xforge": _write_generated_text(
            model_root / "requirements-xforge.txt",
            _default_requirements_xforge(),
        ),
        "requirements_local": _write_generated_text(
            model_root / "requirements-local.txt",
            _default_requirements_local(),
        ),
        "model_py": _write_text_if_missing(
            model_root / "model.py", _default_model_py(normalized_manifest)
        ),
        "server_py": _write_text_if_missing(model_root / "server.py", _default_server_py(task_type), executable=True),
        "validate_py": _write_text_if_missing(model_root / "validate.py", _default_validate_py(), executable=True),
        "init_py": _write_text_if_missing(model_root / "__init__.py", _default_init_py()),
        "local_uv_setup": _write_generated_text(
            model_root / "local_uv_setup.sh",
            _default_local_uv_setup_sh(),
            executable=True,
        ),
        "local_uv_validate": _write_generated_text(
            model_root / "local_uv_validate.sh",
            _default_local_uv_validate_sh(),
            executable=True,
        ),
        "dockerfile": _write_generated_text(model_root / "Dockerfile", _default_dockerfile(model_root)),
        "docker_build": _write_generated_text(
            model_root / "docker_build.sh",
            _default_docker_build_sh(model_root),
            executable=True,
        ),
        "docker_validate": _write_generated_text(
            model_root / "docker_validate.sh",
            _default_docker_validate_sh(model_root),
            executable=True,
        ),
    }

    backend_choice = {
        "chosen_backend": "docker",
        "reason": (
            "XForge only guarantees ModelScope discovery and model-local checkpoint placement; "
            "the SURE model tool-agent should build an isolated runtime before import/load/infer validation."
        ),
        "confidence": "initial_pending_builder_review",
        "evidence": [
            "source provider is ModelScope",
            f"model-local checkpoint directory: {checkpoints_dir.resolve()}",
            f"runtime/cache directory: {runtime_dir.resolve()}",
            f"SURE onboarding contract: {SURE_MODELS_AGENT_CONTRACT}",
        ],
        "rejected_options": [],
        "source_agent": "xforge_modelscope_fetch",
        "target_agent_contract": SURE_MODELS_AGENT_CONTRACT,
        "generated_at": generated_at,
    }
    _write_json(artifacts_dir / "backend_choice.json", backend_choice)

    preflight_summary = _emit_preflight_summary(model_root, checkpoints_dir, runtime_dir)
    local_uv_env = _emit_local_uv_env(model_root)
    spec_validation = _emit_static_spec_validation(model_root, has_weights)
    spec_status = "completed_by_xforge_static_check" if spec_validation["status"] == "passed" else "failed"
    local_uv_status = (
        "completed_by_xforge_local_uv_setup"
        if local_uv_env["status"] == "ready"
        else "generated_pending_execution"
    )
    fetch_status = "completed_by_xforge" if has_weights else "waiting_for_xforge_download"
    docker_build_command = f"sure/models/{model_root.name}/docker_build.sh"
    docker_validate_command = f"sure/models/{model_root.name}/docker_validate.sh"
    build_plan = {
        "instance_id": f"{model_root.name}-xforge-handoff",
        "model": model_root.name,
        "phase": "phase1",
        "generated_at": generated_at,
        "source_agent": "xforge_modelscope_fetch",
        "target_agent": "sure_model_tool_agent",
        "target_agent_contract": SURE_MODELS_AGENT_CONTRACT,
        "resource": {
            "provider": str(source["provider"]),
            "resource_id": str(source["id"]),
            "url": _modelscope_model_url(source),
            "task_type": task_type,
        },
        "backend": "docker",
        "environment_strategy": {
            "package_manager": "SURE model-agent controlled",
            "reason": "remote ModelScope repository dependencies must be validated in an isolated SURE runtime",
            "checkpoint_root": str(checkpoints_dir.resolve()),
            "runtime_root": str(runtime_dir.resolve()),
        },
        "docker": {
            "dockerfile": str((model_root / "Dockerfile").resolve()),
            "build_command": docker_build_command,
            "validate_command": docker_validate_command,
            "status": "draft_generated_waiting_for_user_confirmation",
            "requires_user_confirmation_before_build": True,
        },
        "wrapper": {
            "status": "generated_scaffold_pending_tool_agent",
            "files": ["model.py", "server.py", "__init__.py", "validate.py", "config.yaml"],
        },
        "steps": [
            {
                "state": "VALIDATE_SPEC",
                "owner": "SURE Harness Controller",
                "status": spec_status,
                "inputs": ["model.spec.yaml", "artifacts/backend_choice.json", "artifacts/spec_validation.json"],
                "command": "SURE_XFORGE_STATIC_ONLY=1 .venv/bin/python validate.py",
            },
            {
                "state": "LOCAL_UV_BOOTSTRAP",
                "owner": "XForge ModelScope Fetch / SURE Harness Controller",
                "status": local_uv_status,
                "depends_on": "VALIDATE_SPEC",
                "setup_command": f"sure/models/{model_root.name}/local_uv_setup.sh",
                "validate_command": f"sure/models/{model_root.name}/local_uv_validate.sh",
                "artifacts": [
                    "artifacts/local_uv_env.json",
                    "artifacts/local_uv_validation.json",
                    "artifacts/preflight_summary.json",
                ],
            },
            {
                "state": "DOCKER_BUILD_CONFIRM",
                "owner": "Human",
                "status": "waiting_for_user_confirmation",
                "depends_on": "LOCAL_UV_BOOTSTRAP",
                "decision": "Confirm the generated Dockerfile, requirements-xforge.txt, image tag, GPU/runtime constraints, and whether to run docker_build.sh.",
            },
            {
                "state": "FETCH_WEIGHTS",
                "owner": "XForge ModelScope Fetch",
                "status": fetch_status,
                "weights_manifest": str(weights_manifest_path.resolve()) if has_weights else None,
            },
            {
                "state": "BUILD_ENV",
                "owner": "SURE Builder Agent",
                "status": "blocked_until_user_confirms_docker_build",
                "depends_on": "DOCKER_BUILD_CONFIRM",
                "command": docker_build_command,
            },
            {"state": "VALIDATE_IMPORT", "owner": "SURE Harness Controller", "status": "pending"},
            {"state": "VALIDATE_LOAD", "owner": "SURE Harness Controller", "status": "pending"},
            {"state": "VALIDATE_INFER", "owner": "SURE Harness Controller", "status": "pending"},
            {"state": "VALIDATE_CONTRACT", "owner": "SURE Harness Controller", "status": "pending"},
            {
                "state": "GENERATE_WRAPPER",
                "owner": "SURE Builder Agent",
                "status": "scaffold_generated_pending_model_specific_implementation",
            },
            {"state": "SAVE_ARTIFACTS", "owner": "SURE Harness Controller", "status": "pending"},
        ],
    }
    _write_json(artifacts_dir / "build_plan.json", build_plan)

    tool_agent_request = {
        "source_agent": "xforge_modelscope_fetch",
        "target_agent": "sure_model_tool_agent",
        "target_agent_contract": SURE_MODELS_AGENT_CONTRACT,
        "requested_start_state": "DOCKER_BUILD_CONFIRM",
        "sure_next_state_after_confirmation": "BUILD_ENV",
        "requires_user_confirmation_before_build": True,
        "pending_user_interaction": {
            "state": "DOCKER_BUILD_CONFIRM",
            "continues_to_state": "BUILD_ENV",
            "question": "Confirm generated Dockerfile, requirements-xforge.txt, image tag, GPU/runtime constraints, then approve running docker_build.sh.",
            "default_recommendation": "Review generated Docker artifacts before running the build.",
        },
        "model_dir": str(model_root.resolve()),
        "resource": {
            "provider": str(source["provider"]),
            "resource_id": str(source["id"]),
            "url": _modelscope_model_url(source),
            "task_type": task_type,
        },
        "inputs": {
            "model_spec": str(spec_path.resolve()),
            "backend_choice": str((artifacts_dir / "backend_choice.json").resolve()),
            "build_plan": str((artifacts_dir / "build_plan.json").resolve()),
            "spec_validation": str((artifacts_dir / "spec_validation.json").resolve()),
            "preflight_summary": str((artifacts_dir / "preflight_summary.json").resolve()),
            "local_uv_env": str((artifacts_dir / "local_uv_env.json").resolve()),
            "weights_manifest": str(weights_manifest_path.resolve()) if has_weights else None,
            "xforge_manifest": str(manifest_path.resolve()),
            "xforge_handoff": str(handoff_path.resolve()),
        },
        "generated_scaffold": generated_scaffold,
        "required_actions": [
            {
                "state": "LOCAL_UV_BOOTSTRAP",
                "action": "Use local_uv_setup.sh and local_uv_validate.sh to prepare and verify model-local .venv before Docker build confirmation.",
            },
            {
                "state": "DOCKER_BUILD_CONFIRM",
                "action": "Ask the user to confirm Dockerfile, requirements-xforge.txt, image tag, GPU/runtime constraints, and approval to run docker_build.sh.",
            },
            {
                "state": "BUILD_ENV",
                "action": "Only after user confirmation, revise Dockerfile/pyproject/requirements if needed, then run docker_build.sh.",
            },
            {
                "state": "FETCH_WEIGHTS",
                "action": "Use artifacts/weights_manifest.json if present; otherwise rerun XForge ModelScope fetch without --no-download.",
            },
            {
                "state": "VALIDATE_IMPORT",
                "action": "Replace generated wrapper scaffold with repo-native import/load code and verify imports.",
            },
            {
                "state": "VALIDATE_LOAD",
                "action": "Load the local checkpoint path from weights_manifest.json.",
            },
            {
                "state": "VALIDATE_INFER",
                "action": "Run at least one model-local audio fixture through the wrapper.",
            },
            {
                "state": "VALIDATE_CONTRACT",
                "action": "Verify SURE output fields and JSON serialization contract.",
            },
            {
                "state": "SAVE_ARTIFACTS",
                "action": "Write build.log, validation.log, verdict.json, and final artifact_manifest.json.",
            },
        ],
        "do_not_claim_ready_until": [
            "model-local uv bootstrap is generated and either verified or explicitly recorded as pending/failed",
            "user confirms docker build",
            "model-specific wrapper is implemented",
            "docker build succeeds",
            "import/load/infer/contract validations pass",
            "verdict.json records PASS",
        ],
        "created_at": generated_at,
    }
    _write_json(artifacts_dir / "tool_agent_request.json", tool_agent_request)

    known_artifacts = {
        "model_spec": "present",
        "backend_choice": "present",
        "build_plan": "present",
        "spec_validation": "present" if (artifacts_dir / "spec_validation.json").exists() else "missing",
        "preflight_summary": "present" if (artifacts_dir / "preflight_summary.json").exists() else "missing",
        "local_uv_env": "present" if (artifacts_dir / "local_uv_env.json").exists() else "missing",
        "xforge_sure_handoff": "present",
        "tool_agent_request": "present",
        "config_yaml": "present",
        "pyproject_toml": "present",
        "requirements_xforge": "present",
        "requirements_local": "present",
        "local_uv_setup": "present",
        "local_uv_validate": "present",
        "dockerfile": "present",
        "docker_build": "present",
        "docker_validate": "present",
        "weights_manifest": "present" if has_weights else "missing",
        "build_log": "present" if (artifacts_dir / "build.log").exists() else "missing",
        "validation_log": "present" if (artifacts_dir / "validation.log").exists() else "missing",
        "verdict": "present" if (artifacts_dir / "verdict.json").exists() else "missing",
        "wrapper": "present_scaffold_pending_tool_agent",
        "validate_py": "present_static_scaffold",
        "fixture": "present" if (model_root / "fixture").exists() else "missing",
    }
    artifact_manifest = {
        "instance_id": f"{model_root.name}-xforge-handoff",
        "timestamp": generated_at,
        "model_id": model_root.name,
        "source_agent": "xforge_modelscope_fetch",
        "target_agent_contract": SURE_MODELS_AGENT_CONTRACT,
        "known_artifacts": known_artifacts,
        "paths": {
            "model_dir": str(model_root.resolve()),
            "model_spec": str(spec_path.resolve()),
            "backend_choice": str((artifacts_dir / "backend_choice.json").resolve()),
            "build_plan": str((artifacts_dir / "build_plan.json").resolve()),
            "spec_validation": str((artifacts_dir / "spec_validation.json").resolve()),
            "preflight_summary": str((artifacts_dir / "preflight_summary.json").resolve()),
            "local_uv_env": str((artifacts_dir / "local_uv_env.json").resolve()),
            "tool_agent_request": str((artifacts_dir / "tool_agent_request.json").resolve()),
            "config_yaml": str((model_root / "config.yaml").resolve()),
            "requirements_local": str((model_root / "requirements-local.txt").resolve()),
            "local_uv_setup": str((model_root / "local_uv_setup.sh").resolve()),
            "local_uv_validate": str((model_root / "local_uv_validate.sh").resolve()),
            "dockerfile": str((model_root / "Dockerfile").resolve()),
            "docker_build": str((model_root / "docker_build.sh").resolve()),
            "docker_validate": str((model_root / "docker_validate.sh").resolve()),
            "weights_manifest": str(weights_manifest_path.resolve()) if has_weights else None,
        },
    }
    _write_json(artifacts_dir / "artifact_manifest.json", artifact_manifest)

    sure_handoff = {
        "source_agent": "xforge_modelscope_fetch",
        "target_agent": "sure_model_tool_agent",
        "target_agent_contract": SURE_MODELS_AGENT_CONTRACT,
        "resource_type": "model",
        "provider": str(source["provider"]),
        "resource_id": str(source["id"]),
        "model_name": model_name,
        "task_type": task_type,
        "model_dir": str(model_root.resolve()),
        "checkpoint_dir": str(checkpoints_dir.resolve()),
        "runtime_dir": str(runtime_dir.resolve()),
        "xforge_manifest_path": str(manifest_path.resolve()),
        "xforge_handoff_path": str(handoff_path.resolve()),
        "weights_manifest_path": str(weights_manifest_path.resolve()) if has_weights else None,
        "completed_states": ["DISCOVER", "CLASSIFY", "PLAN", "VALIDATE_SPEC"]
        if spec_validation["status"] == "passed"
        else ["DISCOVER", "CLASSIFY", "PLAN"],
        "xforge_completed_states": ["FETCH_WEIGHTS"] if has_weights else [],
        "next_state": "DOCKER_BUILD_CONFIRM",
        "sure_next_state_after_confirmation": "BUILD_ENV",
        "requires_user_confirmation_before_build": True,
        "pending_user_interaction": {
            "state": "DOCKER_BUILD_CONFIRM",
            "continues_to_state": "BUILD_ENV",
            "question": "Confirm generated Dockerfile, requirements-xforge.txt, image tag, GPU/runtime constraints, then approve running docker_build.sh.",
            "default_recommendation": "Review generated Docker artifacts before running the build.",
        },
        "evaluation_ready": False,
        "blocking_missing_artifacts": [
            name for name, status in known_artifacts.items() if status == "missing"
        ],
        "tool_agent_request_path": str((artifacts_dir / "tool_agent_request.json").resolve()),
        "created_at": generated_at,
    }
    handoff_out_path = artifacts_dir / "xforge_sure_handoff.json"
    _write_json(handoff_out_path, sure_handoff)

    return {
        "resource_type": "model",
        "resource_id": str(source["id"]),
        "model_dir": str(model_root.resolve()),
        "handoff_path": str(handoff_out_path.resolve()),
        "model_spec_path": str(spec_path.resolve()),
        "backend_choice_path": str((artifacts_dir / "backend_choice.json").resolve()),
        "build_plan_path": str((artifacts_dir / "build_plan.json").resolve()),
        "spec_validation_path": str((artifacts_dir / "spec_validation.json").resolve()),
        "artifact_manifest_path": str((artifacts_dir / "artifact_manifest.json").resolve()),
        "tool_agent_request_path": str((artifacts_dir / "tool_agent_request.json").resolve()),
        "weights_manifest_status": "present" if has_weights else "missing",
        "next_state": "DOCKER_BUILD_CONFIRM",
        "sure_next_state_after_confirmation": "BUILD_ENV",
        "requires_user_confirmation_before_build": True,
        "evaluation_ready": False,
    }


def materialize_model_manifest(manifest: dict[str, Any], model_dir: str | Path) -> dict[str, Any]:
    """Materialize an XForge model source into SURE model-local artifacts."""

    manifest = _require_mapping(manifest, "manifest")
    _require_fields(manifest, ("resource_type", "model_name", "task_type", "source"), "model manifest")
    if manifest["resource_type"] != "model":
        raise BridgeError("model materialization requires resource_type='model'")

    source = _require_mapping(manifest["source"], "source")
    _require_fields(source, ("provider", "id"), "model source")
    provider = str(source["provider"])
    model_root = Path(model_dir)
    checkpoints_dir = model_root / "checkpoints"
    runtime_dir = model_root / ".runtime"
    artifacts_dir = model_root / "artifacts"
    checkpoints_dir.mkdir(parents=True, exist_ok=True)
    runtime_dir.mkdir(parents=True, exist_ok=True)
    artifacts_dir.mkdir(parents=True, exist_ok=True)

    if provider != "local":
        raise BridgeError(
            "materialize_model_manifest currently expects a locally collected source. "
            "Run scripts/xforge_collect_model.py first for remote providers."
        )

    source_path = Path(str(source["id"]))
    destination = checkpoints_dir / source_path.name
    local_model_path, materialization = _materialize_model_path(
        source_path,
        destination,
        runtime_dir,
        source,
    )
    weights_manifest = {
        "resource_type": "model",
        "model_name": str(manifest["model_name"]),
        "task_type": str(manifest["task_type"]),
        "source": source,
        "cache_policy": "model_local_first",
        "checkpoint_root": str(checkpoints_dir.resolve()),
        "runtime_root": str(runtime_dir.resolve()),
        "resolved_local_model_path": str(local_model_path),
        **materialization,
        "materialized_at": _utc_now(),
        "fallback": None,
    }
    _write_json(artifacts_dir / "weights_manifest.json", weights_manifest)

    return {
        "resource_type": "model",
        "model_name": str(manifest["model_name"]),
        "local_model_path": str(local_model_path),
        "weights_manifest": str((artifacts_dir / "weights_manifest.json").resolve()),
    }


def load_manifest(path: str | Path) -> dict[str, Any]:
    return _read_json(Path(path))


def write_summary(path: str | Path, summary: dict[str, Any]) -> None:
    _write_json(Path(path), summary)
